version: '3'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"  # Blob service port
      - "10001:10001"  # Queue service port
      - "10002:10002"  # Table service port
    volumes:
      - /data
    networks:
      - custom-network  # Define the custom network for Azurite

networks:
  custom-network:  # Define a custom network


# Ref: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio
# Default connectiong string: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;
