name: Run scans and tests on Rust repos

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  ci-ct-job-for-rust-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Test Rust repository
        uses: MGTheTrain/public-github-actions/.github/actions/test-rust-repository-considering-terraform@main
        with:
          CARGO_TOML_DIRECTORY: ./
          TF_DIRECTORY: ./devops/terraform
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}